# version: '3'
services:
  jaeger-all-in-one:
    container_name:   jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin-all-in-one:
    container_name:   zipkin-all-in-one
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

#   prometheus:
#     container_name: prometheus
#     image: prom/prometheus:latest
#     restart: always
#     volumes:      exporters: [otlp, debug]

#       - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.63.1
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension

  servicoa:
    container_name: servicoa
    build:
      context: ./servicoa
    depends_on:
      - jaeger-all-in-one
      - otel-collector
    ports:
      - "8080:8080"
    # command: [ "tail", "-f", "/dev/null" ]

  servicob:
    container_name: servicob
    build:
      context: ./servicob
    depends_on:
      - jaeger-all-in-one
      - otel-collector
    ports:
      - "8081:8081"
    # command: [ "tail", "-f", "/dev/null" ]
