receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
 
  # debug:
    # verbosity: normal # normal, verbose

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [otlp, debug]
      exporters: [otlp]
